### ISSUE TITLE
大佬，有没有尝试加过vue-i18n，我加了以后回报script unsafe错误

### ISSUE THREAD

**Issue by diankourenxia** [TaiAiAc/electron-vue3-quiet#3]
报这个错core-base.esm-bundler.js:827 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".
<img width="496" alt="image" src="https://user-images.githubusercontent.com/15888981/191472438-03dfa704-83e3-4e25-8770-e3374992b2a4.png">

实际meta上'unsafe-eval'已经加了

**Comment by TaiAiAc** [comment]
已经内置了的， [https://github.com/TaiAiAc/electron-vue3-quiet/tree/main/src/renderer/i18n](这个目录下已经封装好了的)
使用方法在 [https://github.com/TaiAiAc/electron-vue3-quiet/blob/main/src/renderer/pages/Test/i18n.vue](这里)
